# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6b1a53cb07efb23b170fdf41583be79fd3f0f2c8910577502908437ac2b7df12407b3d86ccfbf422ff08154a98bccd5a2f013cb00dfdc6b2934b1aefc9d1d996

test:
  secret_key_base: 1fc364fd45bdc4b5d1172219fb486c2a820c2c224aa4d9422bfe0dcebab93b862fc7c71315b11117364480992dd4d7aa72b67a1c9a95c405de22dd000305f4f3

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
